var myModule = angular.module("myModule", ["angularBeans","ngMaterial","ngCookies"])
.controller('CtrlInsc',CtrlInsc)
.controller('CtrlCnx',CtrlCnx)
.controller('profilCtrl',profilCtrl)
.controller('indexCtrl',indexCtrl)
.controller('projetCtrl',projetCtrl)
.controller('InternCtrl',InternCtrl)
.controller('clientCtrl',clientCtrl)
.controller('CltCtrl',CltCtrl)
.controller('MsgCtrl',MsgCtrl)
.controller('SommaireCtrl',SommaireCtrl)
;
